### ISSUE TITLE
Hidding buttons when no window is active (or focused)

### ISSUE THREAD

**Issue by harogaston** [fatihmete/window-buttons-with-title#1]
Hi, I am very enthusiastic about your project. And I was wandering if you have any plans to include an option to hide the window buttons (and title, but this at least I managed to do already) when there are no windows focused/active/selected.

Because it looks weird when the buttons appear in the panel even if there are no windows opened.

I tried to edit the js myself, but coudn't do it, I haven't programmed in Java yet.

Thank you for your time.
Sincerely,

Gastón.

**Comment by lestcape** [comment]
@fatihmete, Cinnamon Maximus: https://github.com/linuxmint/muffin/commit/a6a4518148c09fe774110b8a331c5f228ee3f745

**Comment by ugggf** [comment]
Hey there. Upgrading to Mint 17.3 seems to cause a similar problem to what I had previously posted here. After login it shows "no active window" (expected to show nothing). When moving to an empty workspace the title is stuck to the previous workspace state (expected to show nothing on an empty workspace) and vice versa. Any ideas on that? Thanks!

**Comment by BenjaminDebeerst** [comment]
Hi uggf, 

no idea on the workspace issue, but the "No active window" text was hard-coded. I bothered me too, so I made that text (along with the title for the Desktop) configurable. Here's the pull request if you're interested: https://github.com/fatihmete/window-buttons-with-title/pull/8

Best regards

**Comment by hanspr** [comment]
Editing the applet.js function onlyMaximize like this, will fix it

    onlyMaximize: function(){
        w=global.display.focus_window;
        let tracker = Cinnamon.WindowTracker.get_default();
       	let app = tracker.get_window_app(w);
		let buttons=this.buttons_style.split(':');
		if(app && w.get_maximized()){
			for (let i=0; i < buttons.length; ++i ){
				this.button[buttons[i]].show();
			}
		} else {
			for (let i=0; i < buttons.length; ++i ){
				this.button[buttons[i]].hide();
			}
		}
	},

**Comment by harogaston** [comment]
I will close this as it is outdated.
